// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Promessometro.Infraestrutura.Context;

#nullable disable

namespace Promessometro.Infraestrutura.Migrations
{
    [DbContext(typeof(PromessometroContext))]
    [Migration("20250701095202_AtualizacaoUsuario")]
    partial class AtualizacaoUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Promessometro.Dominio.Fases.Fase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConclusaoPorcentagem")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PromessaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PromessaId");

                    b.ToTable("Fases", (string)null);
                });

            modelBuilder.Entity("Promessometro.Dominio.Promessas.Promessa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConclusaoPorcentagem")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalhes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Promessas", (string)null);
                });

            modelBuilder.Entity("Promessometro.Dominio.Requerimentos.Requerimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Codigo");

                    b.ToTable("Requerimentos", (string)null);
                });

            modelBuilder.Entity("Promessometro.Dominio.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AceitouOsTermos")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaCriptografada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("b024e690-d423-4c3a-b512-00e648419154"),
                            AceitouOsTermos = true,
                            Email = "adm@gmail.com",
                            Nome = "ADMINISTRADOR",
                            SenhaCriptografada = "1h0ATANFe6x7kMHo1PURE74WI0ayevUwfK/+Ie+IWX/xWrFWngcVUwL/ewryn38EMVMQBFaNo4SaVwgXaBWnDw==",
                            Telefone = ""
                        });
                });

            modelBuilder.Entity("Promessometro.Dominio.Vereadores.Vereador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaminhoImagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Partido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vereadores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("eae6ed0d-6f55-42af-964a-2813c768c1cd"),
                            CaminhoImagem = "amelianaomi.jpg",
                            Nome = "Amélia Naomi",
                            Partido = "PT"
                        },
                        new
                        {
                            Id = new Guid("dc4b87e4-ab77-4a21-9ae9-654f8784e882"),
                            CaminhoImagem = "carlosabranches.jpg",
                            Nome = "Carlos Abranches",
                            Partido = "CIDADANIA"
                        },
                        new
                        {
                            Id = new Guid("a0737c88-80af-4322-b80f-f333f034d4d8"),
                            CaminhoImagem = "claudioapolinario.jpg",
                            Nome = "Cláudio Apolinário",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("59292331-80b7-4d63-9205-6b02a02a01e1"),
                            CaminhoImagem = "fabiaozagueiro.jpg",
                            Nome = "Fabião Zagueiro",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("82f2e4bb-16c7-4120-990d-89de1334b43b"),
                            CaminhoImagem = "fernandopetiti.jpg",
                            Nome = "Fernando Petiti",
                            Partido = "PSDB"
                        },
                        new
                        {
                            Id = new Guid("c4cebc7f-7f03-4192-bb16-c9701ed81a69"),
                            CaminhoImagem = "gilsoncampos.jpg",
                            Nome = "Gilson Campos",
                            Partido = "PRD"
                        },
                        new
                        {
                            Id = new Guid("3f0acc8f-1737-4e24-b998-1abb1948cbee"),
                            CaminhoImagem = "julianafraga.jpg",
                            Nome = "Juliana Fraga",
                            Partido = "PT"
                        },
                        new
                        {
                            Id = new Guid("40c7ee39-b72b-4fdf-9616-27aaf823893b"),
                            CaminhoImagem = "linobispo.jpg",
                            Nome = "Lino Bispo",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("bac8fd32-9580-4d84-95e8-299c413d7646"),
                            CaminhoImagem = "marcaodaacademia.jpg",
                            Nome = "Marcão da Academia",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("19038e54-027a-42cf-8ada-7b75dac200e4"),
                            CaminhoImagem = "marcelogarcia.jpg",
                            Nome = "Marcelo Garcia",
                            Partido = "PRD"
                        },
                        new
                        {
                            Id = new Guid("77ea3add-9771-4bd6-827d-93165bc536a1"),
                            CaminhoImagem = "miltonvieirafilho.jpg",
                            Nome = "Milton Vieira Filho",
                            Partido = "REPUBLICANOS"
                        },
                        new
                        {
                            Id = new Guid("12f6fc30-ba32-4d2b-94fe-30182711d346"),
                            CaminhoImagem = "rafaelpascucci.jpg",
                            Nome = "Rafael Pascucci",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("da08182f-d354-4731-b45c-6a27a206842d"),
                            CaminhoImagem = "renatosantiago.jpg",
                            Nome = "Renato Santiago",
                            Partido = "UNIÃO"
                        },
                        new
                        {
                            Id = new Guid("03e9d60f-8ac2-4f02-9a63-3b88ad321498"),
                            CaminhoImagem = "robertochagas.jpg",
                            Nome = "Roberto Chagas",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("2a65ce12-a183-4814-9994-934e93a8c5b7"),
                            CaminhoImagem = "robertodoeleven.jpg",
                            Nome = "Roberto do Eleven",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("50154f04-f133-47cb-91c9-a825a2a2009a"),
                            CaminhoImagem = "rogeriodaacasem.jpg",
                            Nome = "Rogério da Acasem",
                            Partido = "PP"
                        },
                        new
                        {
                            Id = new Guid("8073f8dd-a627-4cc7-81da-1995b47dec01"),
                            CaminhoImagem = "senna.jpg",
                            Nome = "Senna",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("81a6166b-833d-4129-b174-0b6c7b8621f2"),
                            CaminhoImagem = "sergiocamargo.jpg",
                            Nome = "Sérgio Camargo",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("81dab524-b6f6-422d-8c8e-898122153e61"),
                            CaminhoImagem = "sidneycampos.jpg",
                            Nome = "Sidney Campos",
                            Partido = "PSDB"
                        },
                        new
                        {
                            Id = new Guid("20ac281e-8410-42cd-8758-3d46f658f4d0"),
                            CaminhoImagem = "thomazhenrique.jpg",
                            Nome = "Thomaz Henrique",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("0310cc93-cbc6-4939-8938-ebca31ef7adf"),
                            CaminhoImagem = "zeluis.jpg",
                            Nome = "Zé Luís",
                            Partido = "PSD"
                        });
                });

            modelBuilder.Entity("Promessometro.Dominio.Votos.Voto", b =>
                {
                    b.Property<Guid>("VereadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequerimentoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Aprovacao")
                        .HasColumnType("boolean");

                    b.HasKey("VereadorId", "RequerimentoId");

                    b.HasIndex("RequerimentoId");

                    b.ToTable("Votos", (string)null);
                });

            modelBuilder.Entity("Promessometro.Dominio.Fases.Fase", b =>
                {
                    b.HasOne("Promessometro.Dominio.Promessas.Promessa", "Promessa")
                        .WithMany("Fases")
                        .HasForeignKey("PromessaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promessa");
                });

            modelBuilder.Entity("Promessometro.Dominio.Votos.Voto", b =>
                {
                    b.HasOne("Promessometro.Dominio.Requerimentos.Requerimento", "Requerimento")
                        .WithMany("Votos")
                        .HasForeignKey("RequerimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Promessometro.Dominio.Vereadores.Vereador", "Vereador")
                        .WithMany("Votos")
                        .HasForeignKey("VereadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requerimento");

                    b.Navigation("Vereador");
                });

            modelBuilder.Entity("Promessometro.Dominio.Promessas.Promessa", b =>
                {
                    b.Navigation("Fases");
                });

            modelBuilder.Entity("Promessometro.Dominio.Requerimentos.Requerimento", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Promessometro.Dominio.Vereadores.Vereador", b =>
                {
                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
