// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Promessometro.Infraestrutura.Context;

#nullable disable

namespace Promessometro.Infraestrutura.Migrations
{
    [DbContext(typeof(PromessometroContext))]
    [Migration("20250630224017_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Promessometro.Dominio.Fases.Fase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConclusaoPorcentagem")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PromessaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PromessaId");

                    b.ToTable("Fases", (string)null);
                });

            modelBuilder.Entity("Promessometro.Dominio.Promessas.Promessa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConclusaoPorcentagem")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalhes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Promessas", (string)null);
                });

            modelBuilder.Entity("Promessometro.Dominio.Requerimentos.Requerimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Codigo");

                    b.ToTable("Requerimentos", (string)null);
                });

            modelBuilder.Entity("Promessometro.Dominio.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaCriptografada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("32c95da9-f7dc-4a22-94cc-126d43f635ed"),
                            Email = "adm@gmail.com",
                            Nome = "ADMINISTRADOR",
                            SenhaCriptografada = "1h0ATANFe6x7kMHo1PURE74WI0ayevUwfK/+Ie+IWX/xWrFWngcVUwL/ewryn38EMVMQBFaNo4SaVwgXaBWnDw=="
                        });
                });

            modelBuilder.Entity("Promessometro.Dominio.Vereadores.Vereador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaminhoImagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Partido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vereadores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c64b30d-d589-4cc0-bfe8-26cefc6ce658"),
                            CaminhoImagem = "amelianaomi.jpg",
                            Nome = "Amélia Naomi",
                            Partido = "PT"
                        },
                        new
                        {
                            Id = new Guid("36350b02-02e0-408c-8a01-90944da66d77"),
                            CaminhoImagem = "carlosabranches.jpg",
                            Nome = "Carlos Abranches",
                            Partido = "CIDADANIA"
                        },
                        new
                        {
                            Id = new Guid("ad52d164-7bc7-4f63-9d0d-3967927a1cca"),
                            CaminhoImagem = "claudioapolinario.jpg",
                            Nome = "Cláudio Apolinário",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("e864d5db-c515-4235-9c6e-bac04906f1eb"),
                            CaminhoImagem = "fabiaozagueiro.jpg",
                            Nome = "Fabião Zagueiro",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("b3982944-ea36-4b37-9476-6ef2a5f2b326"),
                            CaminhoImagem = "fernandopetiti.jpg",
                            Nome = "Fernando Petiti",
                            Partido = "PSDB"
                        },
                        new
                        {
                            Id = new Guid("901c0e0c-10d9-41ea-9061-b087fa799fba"),
                            CaminhoImagem = "gilsoncampos.jpg",
                            Nome = "Gilson Campos",
                            Partido = "PRD"
                        },
                        new
                        {
                            Id = new Guid("b9c40986-c66f-47fa-a3d5-67746fcbc9db"),
                            CaminhoImagem = "julianafraga.jpg",
                            Nome = "Juliana Fraga",
                            Partido = "PT"
                        },
                        new
                        {
                            Id = new Guid("06872ddd-5f1e-46ff-a461-48f81386d91c"),
                            CaminhoImagem = "linobispo.jpg",
                            Nome = "Lino Bispo",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("7554dbea-a134-407d-a2dc-45edb7b2fe41"),
                            CaminhoImagem = "marcaodaacademia.jpg",
                            Nome = "Marcão da Academia",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("ee11f2a6-716f-4105-8f4f-1b7e32301eaa"),
                            CaminhoImagem = "marcelogarcia.jpg",
                            Nome = "Marcelo Garcia",
                            Partido = "PRD"
                        },
                        new
                        {
                            Id = new Guid("df5b8b4c-15b3-4f7a-b335-e0e0b257ad69"),
                            CaminhoImagem = "miltonvieirafilho.jpg",
                            Nome = "Milton Vieira Filho",
                            Partido = "REPUBLICANOS"
                        },
                        new
                        {
                            Id = new Guid("c414354c-d8a9-48ec-b50c-f1103620aa14"),
                            CaminhoImagem = "rafaelpascucci.jpg",
                            Nome = "Rafael Pascucci",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("cf93cb5b-c549-419c-80eb-282303bc6770"),
                            CaminhoImagem = "renatosantiago.jpg",
                            Nome = "Renato Santiago",
                            Partido = "UNIÃO"
                        },
                        new
                        {
                            Id = new Guid("28fd1d7d-240d-4c69-a6c0-78ab6d83243a"),
                            CaminhoImagem = "robertochagas.jpg",
                            Nome = "Roberto Chagas",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("cb615dae-0e63-4dfb-89da-dffd4760e48d"),
                            CaminhoImagem = "robertodoeleven.jpg",
                            Nome = "Roberto do Eleven",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("726fe199-38bc-4d09-8a83-ac02e94b6ba4"),
                            CaminhoImagem = "rogeriodaacasem.jpg",
                            Nome = "Rogério da Acasem",
                            Partido = "PP"
                        },
                        new
                        {
                            Id = new Guid("202b4562-23c8-4e00-9641-57acacdaf8d6"),
                            CaminhoImagem = "senna.jpg",
                            Nome = "Senna",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("bd77e8be-5150-4a03-b71a-7741165dde5f"),
                            CaminhoImagem = "sergiocamargo.jpg",
                            Nome = "Sérgio Camargo",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("2c62f66e-580f-4335-9aa6-baa668cfb4fc"),
                            CaminhoImagem = "sidneycampos.jpg",
                            Nome = "Sidney Campos",
                            Partido = "PSDB"
                        },
                        new
                        {
                            Id = new Guid("c37256e2-fba5-4487-8ad8-167469da49e4"),
                            CaminhoImagem = "thomazhenrique.jpg",
                            Nome = "Thomaz Henrique",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("44fdf391-0b3f-4bf5-ac0b-baa05f7e8dd8"),
                            CaminhoImagem = "zeluis.jpg",
                            Nome = "Zé Luís",
                            Partido = "PSD"
                        });
                });

            modelBuilder.Entity("Promessometro.Dominio.Votos.Voto", b =>
                {
                    b.Property<Guid>("VereadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequerimentoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Aprovacao")
                        .HasColumnType("boolean");

                    b.HasKey("VereadorId", "RequerimentoId");

                    b.HasIndex("RequerimentoId");

                    b.ToTable("Votos", (string)null);
                });

            modelBuilder.Entity("Promessometro.Dominio.Fases.Fase", b =>
                {
                    b.HasOne("Promessometro.Dominio.Promessas.Promessa", "Promessa")
                        .WithMany("Fases")
                        .HasForeignKey("PromessaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promessa");
                });

            modelBuilder.Entity("Promessometro.Dominio.Votos.Voto", b =>
                {
                    b.HasOne("Promessometro.Dominio.Requerimentos.Requerimento", "Requerimento")
                        .WithMany("Votos")
                        .HasForeignKey("RequerimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Promessometro.Dominio.Vereadores.Vereador", "Vereador")
                        .WithMany("Votos")
                        .HasForeignKey("VereadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requerimento");

                    b.Navigation("Vereador");
                });

            modelBuilder.Entity("Promessometro.Dominio.Promessas.Promessa", b =>
                {
                    b.Navigation("Fases");
                });

            modelBuilder.Entity("Promessometro.Dominio.Requerimentos.Requerimento", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Promessometro.Dominio.Vereadores.Vereador", b =>
                {
                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
