// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Promessometro.Infraestrutura.Context;

#nullable disable

namespace Promessometro.Infraestrutura.Migrations
{
    [DbContext(typeof(PromessometroContext))]
    [Migration("20250701173547_RemoverDescricaoRequerimento")]
    partial class RemoverDescricaoRequerimento
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Promessometro.Dominio.Fases.Fase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConclusaoPorcentagem")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PromessaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PromessaId");

                    b.ToTable("Fases", (string)null);
                });

            modelBuilder.Entity("Promessometro.Dominio.Promessas.Promessa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConclusaoPorcentagem")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalhes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Promessas", (string)null);
                });

            modelBuilder.Entity("Promessometro.Dominio.Requerimentos.Requerimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Codigo");

                    b.ToTable("Requerimentos", (string)null);
                });

            modelBuilder.Entity("Promessometro.Dominio.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AceitouOsTermos")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaCriptografada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8e54ceb0-04ef-41ac-8cc1-e857827ba790"),
                            AceitouOsTermos = true,
                            Email = "adm@gmail.com",
                            Nome = "ADMINISTRADOR",
                            SenhaCriptografada = "1h0ATANFe6x7kMHo1PURE74WI0ayevUwfK/+Ie+IWX/xWrFWngcVUwL/ewryn38EMVMQBFaNo4SaVwgXaBWnDw==",
                            Telefone = ""
                        });
                });

            modelBuilder.Entity("Promessometro.Dominio.Vereadores.Vereador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaminhoImagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Partido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vereadores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c82016c8-1527-4516-a1af-e8007e55fe36"),
                            CaminhoImagem = "amelianaomi.jpg",
                            Nome = "Amélia Naomi",
                            Partido = "PT"
                        },
                        new
                        {
                            Id = new Guid("c7371ee0-c96a-454b-9770-2488b177c782"),
                            CaminhoImagem = "carlosabranches.jpg",
                            Nome = "Carlos Abranches",
                            Partido = "CIDADANIA"
                        },
                        new
                        {
                            Id = new Guid("46b7b815-4dc4-4b04-9943-4e15cb69a3a3"),
                            CaminhoImagem = "claudioapolinario.jpg",
                            Nome = "Cláudio Apolinário",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("f43b2d58-49f1-4dbd-b869-57296870a266"),
                            CaminhoImagem = "fabiaozagueiro.jpg",
                            Nome = "Fabião Zagueiro",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("2a763dee-a189-410f-91d3-08274608cc2c"),
                            CaminhoImagem = "fernandopetiti.jpg",
                            Nome = "Fernando Petiti",
                            Partido = "PSDB"
                        },
                        new
                        {
                            Id = new Guid("fb1109d2-a13b-423e-bf97-a58ad8bd5c88"),
                            CaminhoImagem = "gilsoncampos.jpg",
                            Nome = "Gilson Campos",
                            Partido = "PRD"
                        },
                        new
                        {
                            Id = new Guid("1e918a99-36d5-4d37-b862-eddb4909575b"),
                            CaminhoImagem = "julianafraga.jpg",
                            Nome = "Juliana Fraga",
                            Partido = "PT"
                        },
                        new
                        {
                            Id = new Guid("e41797cc-97bb-467f-b864-632bd495c43f"),
                            CaminhoImagem = "linobispo.jpg",
                            Nome = "Lino Bispo",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("a2ebdaee-25ef-448e-8829-76b9ef6c20f2"),
                            CaminhoImagem = "marcaodaacademia.jpg",
                            Nome = "Marcão da Academia",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("91831de7-6806-4939-9385-5861808b9349"),
                            CaminhoImagem = "marcelogarcia.jpg",
                            Nome = "Marcelo Garcia",
                            Partido = "PRD"
                        },
                        new
                        {
                            Id = new Guid("4ecc62a7-98fe-40d8-a064-bd40a3eebac1"),
                            CaminhoImagem = "miltonvieirafilho.jpg",
                            Nome = "Milton Vieira Filho",
                            Partido = "REPUBLICANOS"
                        },
                        new
                        {
                            Id = new Guid("4a09d1c3-90e4-4afa-a8b8-18f4a451cec6"),
                            CaminhoImagem = "rafaelpascucci.jpg",
                            Nome = "Rafael Pascucci",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("b38e8455-1d46-490d-9045-60e47b2ed1cb"),
                            CaminhoImagem = "renatosantiago.jpg",
                            Nome = "Renato Santiago",
                            Partido = "UNIÃO"
                        },
                        new
                        {
                            Id = new Guid("c19328e6-5083-40aa-addd-0e5403d1ba15"),
                            CaminhoImagem = "robertochagas.jpg",
                            Nome = "Roberto Chagas",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("8cf43309-6ea6-45fb-8cfd-fa12412ed917"),
                            CaminhoImagem = "robertodoeleven.jpg",
                            Nome = "Roberto do Eleven",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("91243476-d9c0-40bd-a071-aae33fb24f9d"),
                            CaminhoImagem = "rogeriodaacasem.jpg",
                            Nome = "Rogério da Acasem",
                            Partido = "PP"
                        },
                        new
                        {
                            Id = new Guid("2792b548-f56a-4df8-a10d-c74136104b29"),
                            CaminhoImagem = "senna.jpg",
                            Nome = "Senna",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("613f5f6d-8e5c-43c7-be78-6c5981f65ad1"),
                            CaminhoImagem = "sergiocamargo.jpg",
                            Nome = "Sérgio Camargo",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("a2f79f19-a026-46fd-9e6c-70fc8e696979"),
                            CaminhoImagem = "sidneycampos.jpg",
                            Nome = "Sidney Campos",
                            Partido = "PSDB"
                        },
                        new
                        {
                            Id = new Guid("47f336a2-05d6-43e0-9d54-9ca34d79fcdf"),
                            CaminhoImagem = "thomazhenrique.jpg",
                            Nome = "Thomaz Henrique",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("0d5c5cea-aea7-44ab-93e7-3b93b284839a"),
                            CaminhoImagem = "zeluis.jpg",
                            Nome = "Zé Luís",
                            Partido = "PSD"
                        });
                });

            modelBuilder.Entity("Promessometro.Dominio.Votos.Voto", b =>
                {
                    b.Property<Guid>("VereadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequerimentoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Aprovacao")
                        .HasColumnType("boolean");

                    b.HasKey("VereadorId", "RequerimentoId");

                    b.HasIndex("RequerimentoId");

                    b.ToTable("Votos", (string)null);
                });

            modelBuilder.Entity("Promessometro.Dominio.Fases.Fase", b =>
                {
                    b.HasOne("Promessometro.Dominio.Promessas.Promessa", "Promessa")
                        .WithMany("Fases")
                        .HasForeignKey("PromessaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promessa");
                });

            modelBuilder.Entity("Promessometro.Dominio.Votos.Voto", b =>
                {
                    b.HasOne("Promessometro.Dominio.Requerimentos.Requerimento", "Requerimento")
                        .WithMany("Votos")
                        .HasForeignKey("RequerimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Promessometro.Dominio.Vereadores.Vereador", "Vereador")
                        .WithMany("Votos")
                        .HasForeignKey("VereadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requerimento");

                    b.Navigation("Vereador");
                });

            modelBuilder.Entity("Promessometro.Dominio.Promessas.Promessa", b =>
                {
                    b.Navigation("Fases");
                });

            modelBuilder.Entity("Promessometro.Dominio.Requerimentos.Requerimento", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Promessometro.Dominio.Vereadores.Vereador", b =>
                {
                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
