// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Promessometro.Infraestrutura.Context;

#nullable disable

namespace Promessometro.Infraestrutura.Migrations
{
    [DbContext(typeof(PromessometroContext))]
    [Migration("20250825221143_adicionandopromessas")]
    partial class adicionandopromessas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Promessometro.Dominio.Fases.Fase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConclusaoPorcentagem")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PromessaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PromessaId");

                    b.ToTable("Fases", (string)null);
                });

            modelBuilder.Entity("Promessometro.Dominio.Promessas.Promessa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConclusaoPorcentagem")
                        .HasColumnType("integer");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Detalhes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Promessas", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("1dcbd85b-93c0-48c4-bea8-15bdaa24e305"),
                            ConclusaoPorcentagem = 10,
                            Descricao = "Implantação de um novo hospital público na zona sul de São José dos Campos em colaboração com a Santa Casa. O projeto envolve a doação de terreno municipal (antigo prédio do Pró‑Visão) à instituição, que deve construir e operar o hospital, com parte da estrutura atendendo ao SUS e outra parte podendo ser utilizada por atendimentos privados/complementares, além da realocação de uma UBS no complexo",
                            Detalhes = "",
                            Titulo = "Construir o Novo Hospital da Região Sul, em parceria com a Santa Casa, ampliando o atendimento à população."
                        },
                        new
                        {
                            Id = new Guid("5d609876-79c6-4fc5-9a17-ba87915672be"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Finalizar a expansão do Hospital de Clínicas Sul, localizado no Parque Industrial de São José dos Campos, incluindo a criação de 82 novos leitos e salas de cirurgia, com o objetivo de aumentar a capacidade de atendimento hospitalar e cirúrgico da região.",
                            Detalhes = "",
                            Titulo = "Concluir a ampliação do Hospital de Clínicas Sul, no Parque Industrial, com mais 82 leitos e salas de cirurgia."
                        },
                        new
                        {
                            Id = new Guid("faa2918b-ef88-4acd-9a3d-2e1350f6e284"),
                            ConclusaoPorcentagem = 5,
                            Descricao = "Implantação de um centro de diagnóstico por imagem (tomografia e ressonância magnética) no Hospital de Clínicas Sul, em cooperação técnica e financeira com o Governo do Estado, visando a ampliação da capacidade de exames de média e alta complexidade.",
                            Detalhes = "",
                            Titulo = "Implantar o Centro de Imagens do Hospital de Clínicas Sul, em parceria com o Governo do Estado de São Paulo."
                        },
                        new
                        {
                            Id = new Guid("347dacf9-99cf-4eb7-8535-9be16db91dca"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "A promessa consiste na construção de uma nova Unidade de Pronto Atendimento (UPA) para ampliar e qualificar o atendimento de urgência e emergência aos moradores da Região Norte de São José dos Campos, especificamente no bairro Alto da Ponte ou em suas imediações.",
                            Detalhes = "",
                            Titulo = "Construir a Nova UPA da Região Norte, no Alto da Ponte."
                        },
                        new
                        {
                            Id = new Guid("9d70d2ac-30ed-472c-a380-b35a582fed69"),
                            ConclusaoPorcentagem = 5,
                            Descricao = "Implantação de uma nova UBS Resolve no bairro Cajuru, com estrutura física moderna, atendimento ambulatorial integrado, exames e acolhimento humanizado, conforme diretrizes do modelo UBS Resolve.",
                            Detalhes = "",
                            Titulo = "Construir a Nova UBS Resolve na região do Cajuru."
                        },
                        new
                        {
                            Id = new Guid("7501540c-d555-4d0d-8518-c953dc829246"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Implantação de uma nova Unidade Básica de Saúde no modelo \"UBS Resolve\", no bairro Pinheirinho dos Palmares, com foco em atendimento integrado, coleta de exames, acolhimento humanizado e infraestrutura moderna para atender à população da região sudeste.",
                            Detalhes = "",
                            Titulo = "Construir a Nova UBS Resolve do Pinheirinho dos Palmares, na região sudeste."
                        },
                        new
                        {
                            Id = new Guid("58d4fff7-10ab-40c4-b3aa-1ce38069127e"),
                            ConclusaoPorcentagem = 25,
                            Descricao = "Finalizar a construção da Unidade Básica de Saúde no modelo UBS Resolve, localizada na Vila Industrial (Rua Mizael Marçal), com estrutura moderna e atendimento ambulatorial integrado, conforme previsão de conclusão no mandato iniciado em 1º de janeiro de 2025.",
                            Detalhes = "",
                            Titulo = "Construir a Nova UBS Resolve da Vila Industrial."
                        },
                        new
                        {
                            Id = new Guid("2c6763ed-cef5-4a9c-85a4-8230cc0cbc7f"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "A promessa visa a construção de uma nova Unidade Básica de Saúde (UBS) com o modelo \"Resolve\" no bairro Jardim Primavera, em São José dos Campos. O objetivo é ampliar e melhorar o acesso aos serviços de saúde primária para os moradores da região, oferecendo um atendimento mais completo e eficiente.",
                            Detalhes = "",
                            Titulo = "Construir a Nova UBS Resolve do Jardim Primavera."
                        },
                        new
                        {
                            Id = new Guid("c74d2a4f-c6c1-4531-9b22-7b0e6c300137"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Implantar uma Unidade Básica de Saúde no modelo “UBS Resolve” no bairro Jardim Santa Hermínia, oferecendo atendimento ambulatorial integrado, coleta de exames, acolhimento humanizado e estrutura moderna para facilitar o acesso à saúde da população local.",
                            Detalhes = "",
                            Titulo = "Construir a Nova UBS Resolve do Jardim Santa Hermínia."
                        },
                        new
                        {
                            Id = new Guid("44affeb1-b2c9-4e66-a75c-94b140a26c6c"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "A promessa é a instalação de uma nova Unidade Básica de Saúde (UBS) no modelo \"Resolve\" dentro do complexo do Novo Hospital da Região Sul, no bairro Bosque dos Eucaliptos. O objetivo é integrar serviços de saúde primária e secundária, oferecendo um atendimento mais completo e acessível à população.",
                            Detalhes = "",
                            Titulo = "Instalar a Nova UBS Resolve do Bosque dos Eucaliptos, no Novo Hospital da Região Sul."
                        },
                        new
                        {
                            Id = new Guid("34af86c4-f4e9-473e-8d16-34b705df1b6f"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Esta promessa de campanha visa a criação de uma Unidade Avançada de Saúde no bairro Jardim República, em São José dos Campos. O objetivo é expandir o acesso e aprimorar os serviços de saúde para os moradores de uma área específica, incluindo os bairros Vila das Flores, Nova República, Cruzeiro do Sul, Santa Edwiges e adjacências. Essa unidade buscaria oferecer atendimento primário e facilitar o acesso da população local a serviços de saúde essenciais.",
                            Detalhes = "",
                            Titulo = "Criar a Unidade Avançada de Saúde no Jardim República para atender a região: Vila das Flores, Nova República, Cruzeiro do Sul, Santa Edwiges e adjacências."
                        },
                        new
                        {
                            Id = new Guid("faeee589-c351-4c12-a786-28c34d3c1d60"),
                            ConclusaoPorcentagem = 10,
                            Descricao = "Esta promessa de campanha visa a criação de uma Unidade Avançada de Saúde no bairro Urbanova, em São José dos Campos. A particularidade dessa unidade é a sua implementação em parceria com a Universidade do Vale do Paraíba (Univap), visando integrar serviços de saúde e possivelmente a expertise acadêmica e de pesquisa da instituição. O intuito é expandir e qualificar o atendimento de saúde para os moradores da região do Urbanova.",
                            Detalhes = "",
                            Titulo = "Criar a Unidade Avançada de Saúde no Urbanova, em parceria com a Univap."
                        },
                        new
                        {
                            Id = new Guid("cc259c28-03ba-4645-9821-10ec08d97a6e"),
                            ConclusaoPorcentagem = 10,
                            Descricao = "Esta promessa de campanha tem como objetivo a criação de um Novo Centro de Especialidades Odontológicas em São José dos Campos. A iniciativa visa expandir e aprimorar os serviços odontológicos especializados oferecidos à população. A promessa faz parte das diretrizes do Plano de Governo sob \"Saúde\" para o ano de 2026, conforme a Lei de Diretrizes Orçamentárias (LDO) 2026.",
                            Detalhes = "",
                            Titulo = "Criar o Novo Centro de Especialidades Odontológicas."
                        },
                        new
                        {
                            Id = new Guid("8336bb8f-d2f6-4871-9616-9f4ec39ef4e2"),
                            ConclusaoPorcentagem = 50,
                            Descricao = "A promessa consiste na construção de um novo centro especializado para reabilitação motora e neurológica, com o objetivo de concentrar os serviços de atendimento e expandir a capacidade de cuidado aos pacientes que necessitam desses tratamentos em São José dos Campos.",
                            Detalhes = "",
                            Titulo = "Criar o Novo Centro de Reabilitação Motora e Neurológica, para centralizar e ampliar o atendimento aos pacientes."
                        },
                        new
                        {
                            Id = new Guid("dc915010-0eab-4bd9-a290-23a40ebd739e"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Esta promessa de campanha visa o estabelecimento de um Hub de Inovação em Saúde em São José dos Campos, localizado no Parque de Inovação Tecnológica (PIT). O objetivo é centralizar e fomentar o desenvolvimento de startups focadas em saúde digital e inteligência artificial.",
                            Detalhes = "",
                            Titulo = "Criar um Hub de Inovação em Saúde, reunindo startups de saúde digital e IA (Inteligência Artificial), no PIT."
                        },
                        new
                        {
                            Id = new Guid("c54ae230-6f1a-44cf-b3ea-7b1611a0962f"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Esta promessa de campanha tem como objetivo expandir a oferta de consultas com especialistas e exames para a população de São José dos Campos, através do ampliação do credenciamento de clínicas particulares pelo poder público.",
                            Detalhes = "",
                            Titulo = "Ampliar o credenciamento de clínicas particulares para oferecer mais consultas com especialistas e exames."
                        },
                        new
                        {
                            Id = new Guid("305c9c29-10cf-46cf-b750-07502f55e741"),
                            ConclusaoPorcentagem = 10,
                            Descricao = "Esta promessa de campanha visa a expansão dos serviços oferecidos pelo programa Previna, em São José dos Campos, com o objetivo de assegurar que o diagnóstico e o tratamento de pacientes com câncer sejam realizados em um prazo máximo de 60 dias. A iniciativa busca agilizar o acesso a esses cuidados essenciais.",
                            Detalhes = "",
                            Titulo = "Ampliar o atendimento no Previna, com o diagnóstico e o tratamento do paciente com câncer em até 60 dias."
                        },
                        new
                        {
                            Id = new Guid("1302c617-1c83-411c-9d6f-66941037bc5c"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "A promessa visa expandir o programa de fornecimento de fraldas, dietas e fórmulas infantis para atender um número maior de pacientes necessitados no município de São José dos Campos. O objetivo é aumentar o acesso a esses itens essenciais para a saúde e bem-estar de crianças e outros pacientes que dependem deles.",
                            Detalhes = "",
                            Titulo = "Fralda em casa, dietas e fórmulas infantis: ampliar o programa para atendimento de mais pacientes."
                        },
                        new
                        {
                            Id = new Guid("9853af84-c3fc-4347-ac6a-8f6acc914a11"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "A promessa tem como objetivo implementar um programa para a entrega de medicamentos de alto custo e de uso contínuo diretamente na residência dos pacientes em São José dos Campos, visando facilitar o acesso e a adesão ao tratamento, especialmente para aqueles com dificuldades de locomoção ou que dependem de medicações específicas.",
                            Detalhes = "",
                            Titulo = "Medicação em casa: entrega de medicamentos de alto custo e uso crônico na casa dos pacientes."
                        },
                        new
                        {
                            Id = new Guid("cb26cdbb-2010-489b-ac98-52854ba8f7f4"),
                            ConclusaoPorcentagem = 25,
                            Descricao = "A promessa visa expandir a capacidade de atendimento do Serviço de Atendimento Móvel de Urgência (Samu) em São José dos Campos, o que pode envolver o aumento da frota de veículos, a contratação de mais profissionais, a melhoria da infraestrutura ou a otimização dos processos para cobrir uma área maior ou atender mais ocorrências com maior agilidade.",
                            Detalhes = "",
                            Titulo = "Ampliar o atendimento do Samu."
                        },
                        new
                        {
                            Id = new Guid("89a2156e-d446-4108-b26f-97eda6eb00dd"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "A promessa prevê a expansão do serviço de Motolância em São José dos Campos, buscando otimizar o tempo de resposta em atendimentos de emergência. Isso seria alcançado por meio de uma parceria entre a Prefeitura, o Corpo de Bombeiros e o Samu, visando aprimorar a agilidade e a eficácia no socorro a pacientes.",
                            Detalhes = "",
                            Titulo = "Motolância: ampliar o atendimento aos pacientes, numa parceria da Prefeitura/Corpo de Bombeiros/Samu."
                        },
                        new
                        {
                            Id = new Guid("4bd2985b-467e-4de9-ba4f-a6afce5cee59"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "A promessa visa aumentar o número de profissionais de saúde, especificamente médicos e enfermeiros, na rede pública de São José dos Campos para melhorar o atendimento à população.",
                            Detalhes = "",
                            Titulo = "Contratar mais médicos e enfermeiros."
                        },
                        new
                        {
                            Id = new Guid("7f5c39b6-922e-4cf4-bf14-d74453bf403e"),
                            ConclusaoPorcentagem = 5,
                            Descricao = "A promessa tem como objetivo expandir a oferta e a capacidade dos serviços de saúde prestados remotamente por meio da telemedicina em São José dos Campos, visando facilitar o acesso da população a consultas e atendimentos médicos.",
                            Detalhes = "",
                            Titulo = "Ampliar o atendimento de telemedicina."
                        },
                        new
                        {
                            Id = new Guid("94efbe12-510d-4197-829e-73d501bddc3b"),
                            ConclusaoPorcentagem = 20,
                            Descricao = "A promessa visa aumentar o número e a capacidade das equipes de Saúde da Família em São José dos Campos, com o objetivo de fortalecer a atenção primária e ampliar a cobertura do atendimento de saúde para a população.",
                            Detalhes = "",
                            Titulo = "Ampliar as Equipes de Saúde da Família."
                        },
                        new
                        {
                            Id = new Guid("86fc9f31-3477-4613-9e64-73ffb85c8428"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "A promessa tem como objetivo aumentar a capacidade e a qualidade dos serviços de saúde mental oferecidos nos hospitais Francisca Júlia e Chuí, proporcionando um atendimento mais abrangente e especializado para a população de São José dos Campos.",
                            Detalhes = "",
                            Titulo = "Ampliar o atendimento especializado de Saúde Mental, nos hospitais Francisca Júlia e Chuí."
                        },
                        new
                        {
                            Id = new Guid("71f52d8a-8587-4478-9ce8-1a7799c28bd0"),
                            ConclusaoPorcentagem = 50,
                            Descricao = "A promessa visa garantir a continuidade da presença e do trabalho de psicólogos e assistentes sociais nas unidades escolares de São José dos Campos, oferecendo suporte psicossocial e assistência social aos alunos e à comunidade escolar.",
                            Detalhes = "",
                            Titulo = "Manter o atendimento de psicólogos e assistentes sociais nas escolas."
                        },
                        new
                        {
                            Id = new Guid("8060d2eb-e417-441e-bbeb-eceb551ddc9c"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "A promessa visa expandir a capacidade de testagem e detecção de Infecções Sexualmente Transmissíveis em São José dos Campos, por meio da implementação ou ampliação de um serviço de testagem móvel, facilitando o acesso da população aos exames preventivos.",
                            Detalhes = "",
                            Titulo = "Ampliar o serviço de testagem de IST (Infecções Sexualmente Transmissíveis) com serviço móvel."
                        },
                        new
                        {
                            Id = new Guid("2c04abc1-b9a4-4643-b09b-50dbff770593"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "A promessa visa expandir a capacidade de testagem e detecção de Infecções Sexualmente Transmissíveis em São José dos Campos, por meio da implementação ou ampliação de um serviço de testagem móvel, facilitando o acesso da população aos exames preventivos.",
                            Detalhes = "",
                            Titulo = "Ampliar o serviço de testagem de IST (Infecções Sexualmente Transmissíveis) com serviço móvel."
                        },
                        new
                        {
                            Id = new Guid("70d7e5c6-e96f-468d-a2da-c7bf38b4a846"),
                            ConclusaoPorcentagem = 5,
                            Descricao = "Implantar e integrar um sistema municipal de prontuário eletrônico do paciente para registrar e consolidar históricos médicos e exames em formato digital e unificado, facilitando o acesso e gestão na rede de saúde municipal.",
                            Detalhes = "",
                            Titulo = "Prontuário eletrônico: consolidar o sistema de informações do histórico do paciente e exames."
                        },
                        new
                        {
                            Id = new Guid("a337263e-1a73-4d89-94d9-1cb9d8fca4e3"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "A promessa visa atualizar e aprimorar o aplicativo \"Saúde na Mão\" de São José dos Campos, incorporando novas funcionalidades e serviços para torná-lo mais útil e intuitivo, facilitando o acesso dos usuários a informações e atendimentos de saúde.",
                            Detalhes = "",
                            Titulo = "Saúde na Mão: modernizar o aplicativo para oferecer mais serviços e facilitar a vida dos usuários."
                        },
                        new
                        {
                            Id = new Guid("198e94f1-4f9c-4581-93ff-5d32360bee16"),
                            ConclusaoPorcentagem = 100,
                            Descricao = "São José Social: a exemplo do Programa São José Unida, desenvolver ações",
                            Detalhes = "",
                            Titulo = "Ações integradas usuários de drogas"
                        },
                        new
                        {
                            Id = new Guid("8b71c2c2-3e64-4973-a7ac-b7bee2563862"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Ampliar as vagas de internação para o tratamento da dependência química.",
                            Detalhes = "",
                            Titulo = "Aumentar vagas de internação"
                        },
                        new
                        {
                            Id = new Guid("1828d94a-013a-4fe2-99bc-d9fadbab8fc0"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Oferecer atendimento psicológico e social online para dar suporte aos",
                            Detalhes = "",
                            Titulo = "Atendimento psicológico a dependentes químicos"
                        },
                        new
                        {
                            Id = new Guid("e22643bf-1a13-4130-8f02-560a0d4f84f7"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Criar a Casa de Passagem para pessoa em situação de rua",
                            Detalhes = "",
                            Titulo = "Casa de Passagem"
                        },
                        new
                        {
                            Id = new Guid("0cfdfceb-e47a-48ee-94d1-96351302645d"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Fortalecer a Ronda de Apoio Social, 24h, em todas as regiões da cidade.",
                            Detalhes = "",
                            Titulo = "Ronda de Apoio Social"
                        },
                        new
                        {
                            Id = new Guid("61d7b778-176d-4ca7-9e65-2be2e4a25505"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Fortalecer e intensificar o Programa “Não Dê Esmola, Dê Cidadania”.",
                            Detalhes = "",
                            Titulo = "Programa “Não Dê Esmola, Dê Cidadania”"
                        },
                        new
                        {
                            Id = new Guid("41e02f04-5e84-431b-87a3-3469a473c36d"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Viabilizar a abertura de mais uma unidade do Bom Prato em São José dos",
                            Detalhes = "",
                            Titulo = "Bom Prato"
                        },
                        new
                        {
                            Id = new Guid("b4c9444d-de46-4c9f-9029-2c1c7fe4885c"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Fazer acompanhamento social e promover oficinas de capacitação",
                            Detalhes = "",
                            Titulo = "Capacitação para moradores de conjuntos habitacionais"
                        },
                        new
                        {
                            Id = new Guid("90dda066-9bc7-4e5c-bb53-a5ed23c90a30"),
                            ConclusaoPorcentagem = 100,
                            Descricao = "Fortalecer o Peti (Programa de Erradicação do Trabalho Infantil),",
                            Detalhes = "",
                            Titulo = "Peti (Programa de Erradicação do Trabalho Infantil)"
                        },
                        new
                        {
                            Id = new Guid("3c335b3b-7a3f-4a9f-849f-aa10c56625e9"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Criar a Casa da Família Joseense: com a possibilidade de agregar no",
                            Detalhes = "",
                            Titulo = "Casa da Família Joseense"
                        },
                        new
                        {
                            Id = new Guid("1e7f4e02-80a2-4526-8b81-bdf4c23ce033"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Construir a Nova Unidade do Cras, no Campo dos Alemães.",
                            Detalhes = "",
                            Titulo = "Cras (Centro de Referência da Assistência Social)"
                        },
                        new
                        {
                            Id = new Guid("5e25fb6d-ea54-4b83-8a58-3a5e9996989b"),
                            ConclusaoPorcentagem = 100,
                            Descricao = "Consolidar as parcerias com as entidades sociais e com o Fundo Social de",
                            Detalhes = "",
                            Titulo = "Parcerias com o Fundo Social de Solidariedade e entidades sociais"
                        },
                        new
                        {
                            Id = new Guid("9c102965-685c-42ff-803f-7564c889d1fe"),
                            ConclusaoPorcentagem = 75,
                            Descricao = "Esta promessa de campanha foca na gestão financeira e de recursos humanos da prefeitura, garantindo o pagamento pontual dos salários dos servidores públicos e a manutenção do gatilho salarial, que assegura reajustes automáticos conforme determinados indicadores de inflação.",
                            Detalhes = "",
                            Titulo = "Manter os salários em dia e o gatilho salarial do servidor."
                        },
                        new
                        {
                            Id = new Guid("c599221b-2267-404e-840e-513bbee28062"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "A promessa de campanha visa assegurar a distribuição de cestas de alimentos, ou um benefício equivalente, para a população de São José dos Campos durante o período natalino. O objetivo é proporcionar apoio alimentar às famílias em vulnerabilidade social no final do ano.",
                            Detalhes = "",
                            Titulo = "Garantir a cesta de Natal."
                        },
                        new
                        {
                            Id = new Guid("0fdd729f-4446-4c29-95a0-c2695444ecdb"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "A promessa consiste na abertura e execução de processos seletivos para o preenchimento de vagas no quadro de servidores da Prefeitura de São José dos Campos, visando a contratação de novos profissionais para diversas áreas da administração pública. Progresso: 75%",
                            Detalhes = "",
                            Titulo = "Realizar concurso público."
                        },
                        new
                        {
                            Id = new Guid("e0c7f1c2-7fed-40ff-a7e2-6eecafb16602"),
                            ConclusaoPorcentagem = 25,
                            Descricao = "Esta promessa de campanha visa fortalecer o quadro de profissionais da saúde no município de São José dos Campos, por meio da realização de um concurso público específico para a contratação de médicos e enfermeiros, com o intuito de aprimorar os serviços de saúde oferecidos à população.",
                            Detalhes = "",
                            Titulo = "Realizar concurso público para contratar mais médicos e enfermeiros."
                        },
                        new
                        {
                            Id = new Guid("951f9d3d-f47b-43d9-aa38-b5fe43984175"),
                            ConclusaoPorcentagem = 5,
                            Descricao = "Realizar concursos públicos e/ou processos seletivos para contratação efetiva de professores e agentes educadores na rede municipal de ensino, com o objetivo de fortalecer a educação pública com quadro estabilizado e adequado às demandas escolares atuais.",
                            Detalhes = "",
                            Titulo = "Realizar concurso público para contratar mais professores e agentes educadores."
                        },
                        new
                        {
                            Id = new Guid("0bed51e6-dc27-4e9f-a943-4e0ba82dfd34"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "A promessa visa estabelecer uma instituição dedicada à formação e aprimoramento contínuo de profissionais da área da saúde em São José dos Campos, com o objetivo de elevar a qualidade dos serviços prestados à população.",
                            Detalhes = "",
                            Titulo = "Criar a Escola de Formação em Saúde, um centro de treinamento para qualificar os profissionais da área."
                        },
                        new
                        {
                            Id = new Guid("49231416-5c4d-440e-88b5-0d77fa2bd3e9"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "A promessa foca em assegurar a continuidade e impulsionar programas de aprimoramento profissional e educacional para docentes e gestores da rede de ensino de São José dos Campos, visando a melhoria da qualidade da educação.",
                            Detalhes = "",
                            Titulo = "Manter e estimular as atividades de formação continuada para professores e gestores."
                        },
                        new
                        {
                            Id = new Guid("e05aa6a0-e952-4b8f-8fbf-a64f2f461382"),
                            ConclusaoPorcentagem = 100,
                            Descricao = "A promessa visa assegurar a continuidade e o aprimoramento constante do treinamento da Guarda Civil Municipal (GCM) de São José dos Campos, utilizando a estrutura da academia de formação para garantir a qualificação e atualização dos profissionais.",
                            Detalhes = "",
                            Titulo = "Manter o treinamento contínuo dos GCMs por meio da academia de formação."
                        },
                        new
                        {
                            Id = new Guid("a1e621fe-d458-469f-9735-eb43a3f08122"),
                            ConclusaoPorcentagem = 100,
                            Descricao = "A proposta prevê a continuidade do benefício de bolsa de estudos para servidores municipais, com análise e concessão de bolsas educacionais ou acadêmicas destinadas aos servidores e seus dependentes, conforme critérios estabelecidos pela Prefeitura.",
                            Detalhes = "",
                            Titulo = "Manter o programa de bolsa de estudos para os servidores."
                        },
                        new
                        {
                            Id = new Guid("f18cae55-3f16-48ac-8852-74652e5a500a"),
                            ConclusaoPorcentagem = 30,
                            Descricao = "A promessa tem por objetivo assegurar que o IPSM continue com sua saúde fiscal, realizando os aportes necessários e mantendo em dia o pagamento de aposentadorias e pensões dos servidores municipais, de forma regular e tempestiva.",
                            Detalhes = "",
                            Titulo = "Manter as contas do IPSM (Instituto de Previdência do Servidor Municipal) em dia, garantindo as aposentadorias e pensões."
                        },
                        new
                        {
                            Id = new Guid("f004a1ca-a1a7-4fb9-a001-8541a408afe7"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "A construção ainda não foi iniciada, o que existe é um convênio da prefeitura com uma empressa limitado a quem é cadastrado no Cad Único",
                            Detalhes = "",
                            Titulo = "Construir Hospital Público Veterinário"
                        },
                        new
                        {
                            Id = new Guid("ab6d3972-550e-40f5-b33d-f0a6b694fc76"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Construção não iniciada, porém já existe lei sancionada no Diário Oficial pra essa finalidade, restando agora liberação de recursos orçamentários para a obra.",
                            Detalhes = "",
                            Titulo = "Contrução do novo CCZ (Centro de Controle de Zoonozes)"
                        },
                        new
                        {
                            Id = new Guid("11d1ea67-aa00-4073-8ef0-48944ee364e3"),
                            ConclusaoPorcentagem = 100,
                            Descricao = "Sim, foi ampliado para mais de 1000 vagas por edição, o que é um aumento considerável. Porém, os tutores devem ficar atentos pois as vagas se esgotam muito rápido. Em 2025 já foram realizadas 3 edições de castração e microchipagem diretamente no CCZ.",
                            Detalhes = "",
                            Titulo = "Ampliar o atendimento gratuito do Meu Pet Feliz, programa permanente de castração e chipagem de animais"
                        },
                        new
                        {
                            Id = new Guid("370cba56-d9df-4603-bc97-a300d5c1bfb4"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Não há registro de construções de novos espaços caninos até o momento em 2025. Atualmente existem 16 pela cidade.",
                            Detalhes = "",
                            Titulo = "Construção de novos Espaços Caninos"
                        },
                        new
                        {
                            Id = new Guid("26a4da1e-fc31-46e3-be61-73cf49c3f9db"),
                            ConclusaoPorcentagem = 100,
                            Descricao = "Sim, a prefeitura realiza campanha de adoção todos os meses, sempre no último sábado de cada mês. O local é sempre no CCZ.",
                            Detalhes = "",
                            Titulo = "Promover campanhas de doação de animais e a posse responsável"
                        },
                        new
                        {
                            Id = new Guid("b32613fe-a528-4ee9-a156-5825a8514d79"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Não há registro dessas campanhas no ano de 2025 até o momento. A última ocorreu em abril de 2024",
                            Detalhes = "",
                            Titulo = "Promover campanha de adoção de animais de médio e grande porte"
                        },
                        new
                        {
                            Id = new Guid("0a20d30b-846a-4671-bc08-63fdbe99d83f"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Não há registro de ampliação desse programa, apenas a manutenção dos serviços já oferecidos",
                            Detalhes = "",
                            Titulo = "Ampliar o programa de distribuição gratuita de vacinação de animais contra a brucelose, raiva do rebanho etc"
                        },
                        new
                        {
                            Id = new Guid("6b9ad635-d16a-41b4-af51-482b6dd8e629"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Não há registro de instalação de um PEV específico na região do Cajuru até o momento. A lista oficial de PEVs da cidade não inclui essa localidade.",
                            Detalhes = "",
                            Titulo = "Instalar um PEV (Ponto de Entrega Voluntária) na região do Cajuru"
                        },
                        new
                        {
                            Id = new Guid("2b0d4cca-17e0-40b9-96f9-3c2a7d774c1b"),
                            ConclusaoPorcentagem = 50,
                            Descricao = "Houve ampliação do horário de funcionamento e realocação de unidades para melhor atendimento, como no PEV do Campo dos Alemães. Porém, não há expansão significativa em número de unidades.",
                            Detalhes = "",
                            Titulo = "Ampliar, modernizar e melhorar a gestão dos PEVs"
                        },
                        new
                        {
                            Id = new Guid("28c37e7f-ff3e-4678-be2d-176c57e19658"),
                            ConclusaoPorcentagem = 100,
                            Descricao = "A meta foi cumprida. 100% da rede pública já utiliza LED, com constante ampliação para áreas verdes, praças e espaços de lazer em todas as regiões.",
                            Detalhes = "",
                            Titulo = "Manter e ampliar a iluminação de LED em toda área urbana (praças, áreas verdes e ciclovia) e rural."
                        },
                        new
                        {
                            Id = new Guid("e7a29819-f199-4546-98d3-9379b1a3391e"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Não há registro público ou anúncio oficial de caminhões elétricos em operação no sistema de coleta urbana de São José dos Campos",
                            Detalhes = "",
                            Titulo = "Ampliar a implantação de caminhões elétricos para a coleta de lixo"
                        },
                        new
                        {
                            Id = new Guid("9013e776-dc48-47b6-9e14-2a790806605c"),
                            ConclusaoPorcentagem = 30,
                            Descricao = "Foi implantado projeto piloto no centro da cidade (Rua Siqueira Campos e Praça João Mendes). Porém, não houve expansão para outras regiões.",
                            Detalhes = "",
                            Titulo = "Ampliar o sistema de lixeiras subterrâneas para coleta em pontos de grande concentração de resíduos"
                        },
                        new
                        {
                            Id = new Guid("6182086a-1b14-4255-b097-1bea18ce8fc0"),
                            ConclusaoPorcentagem = 50,
                            Descricao = "Contêineres metálicos grandes foram instalados no centro da cidade, em pontos com alta geração de resíduos. Não houve expansão para bairros.",
                            Detalhes = "",
                            Titulo = "Coleta com containers em pontos de alta concentração de resíduos"
                        },
                        new
                        {
                            Id = new Guid("e7c89034-8ecf-4162-b8f8-95a2cef0901d"),
                            ConclusaoPorcentagem = 70,
                            Descricao = "Diversas praças e parquinhos receberam piso emborrachado e novos brinquedos, mas ainda não há menção clara sobre brinquedos inclusivos em larga escala.",
                            Detalhes = "",
                            Titulo = "Ampliar a modernização dos parques infantis com novos brinquedos, brinquedos inclusivos e piso de borracha"
                        },
                        new
                        {
                            Id = new Guid("9769aedf-c0db-4559-833a-be078a5c8f7b"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Não há informações oficiais ou evidências públicas de obras de manutenção ou melhorias em estradas rurais nos anos recentes.",
                            Detalhes = "",
                            Titulo = "Fazer manutenção e melhorias nas estradas rurais"
                        },
                        new
                        {
                            Id = new Guid("acaf5846-4523-4d0d-afce-ed7cf3dd1847"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Não há confirmação de substituição das lixeiras convencionais por contêineres na zona rural até o momento.",
                            Detalhes = "",
                            Titulo = "Melhorar a coleta de lixo na zona rural, substituindo as lixeiras por contêineres"
                        },
                        new
                        {
                            Id = new Guid("31459779-afd6-4ff9-baa2-ce5de7356ee6"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Não há registro da instalação de borrifadores em praças ou parques da cidade.",
                            Detalhes = "",
                            Titulo = "Equipar praças e parques com borrifadores para refrescar as crianças e os adultos neste clima de tempo seco"
                        },
                        new
                        {
                            Id = new Guid("3ab3ba9d-6a81-49ea-8fb7-2a86a158db1e"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Não foram encontrados registros de obras iniciadas ou concluídas nessa área.",
                            Detalhes = "",
                            Titulo = "Criar um novo deck e urbanizar a área verde da Vila Flores, na região sul, com pista de caminhada, quadra esportiva, bancos e área de lazer para as crianças"
                        },
                        new
                        {
                            Id = new Guid("75e87c60-9680-48f1-b0ba-38c23bc42cc4"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "A cidade ampliou a iluminação em diversas ciclovias, mas não há confirmação específica de que essa ciclovia recebeu nova iluminação.",
                            Detalhes = "",
                            Titulo = "Melhorar a iluminação da ciclovia na avenida Altos do Rio Doce, no Altos de Santana, beirando o Rio Paraíba"
                        },
                        new
                        {
                            Id = new Guid("05b23d71-285f-4102-a6cb-a5d00400522a"),
                            ConclusaoPorcentagem = 33,
                            Descricao = "A Praça Rubens Castilho foi revitalizada, mas não há obras visíveis ou confirmadas nas demais áreas citadas.",
                            Detalhes = "",
                            Titulo = "Criar novos decks e revitalizar áreas verdes (Via Cambuí, Praça Rubens Castilho, Mirante no Talude da Veibras)."
                        },
                        new
                        {
                            Id = new Guid("ebae5e19-b4bf-43ab-be91-68ae3a09958a"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Não há registro de revitalização das fontes nessas áreas, apenas intervenções relacionadas a lixeiras subterrâneas.",
                            Detalhes = "",
                            Titulo = "Revitalizar as fontes na região central, Praça João Mendes (Praça do Sapo) e ao lado da Univap."
                        },
                        new
                        {
                            Id = new Guid("369186a3-3e99-48c4-9d9c-820205374134"),
                            ConclusaoPorcentagem = 50,
                            Descricao = "O Jardim Satélite recebeu melhorias em anos anteriores. Vista Verde ainda não apresenta registro recente de intervenções.",
                            Detalhes = "",
                            Titulo = "Revitalizar as áreas verdes do Vista Verde e Jardim Satélite, com melhoria de iluminação, jardinagem e passeio público."
                        },
                        new
                        {
                            Id = new Guid("220570bd-a247-4e91-972c-1bd725514aa8"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Não há comprovação de que a iluminação nesse trecho da SP-50 foi implantada até o momento.",
                            Detalhes = "",
                            Titulo = "Implantar nova iluminação na SP-50, do bairro Boa Vista até o Buquirinha 1"
                        },
                        new
                        {
                            Id = new Guid("ab025ed4-8dcb-4dc9-950f-5c7f4a82cd00"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Construção de uma nova unidade da Casa do Idoso na região sul.",
                            Detalhes = "",
                            Titulo = "Construir mais uma Casa do Idoso na região sul"
                        },
                        new
                        {
                            Id = new Guid("46506ecd-e1e6-4fd4-b5ce-64677e423013"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Viabilizar, com a CDHU/Estado, moradias assistidas para idosos em vulnerabilidade.",
                            Detalhes = "",
                            Titulo = "Programa Vida Longa (CDHU) — moradias para idosos"
                        },
                        new
                        {
                            Id = new Guid("1424775e-ae1c-4a5e-a705-fd8a4d62b0a3"),
                            ConclusaoPorcentagem = 50,
                            Descricao = "Implantação do CER III no Bosque dos Eucaliptos (atrás da Casa do Idoso Sul).",
                            Detalhes = "",
                            Titulo = "Criar o novo CER (Centro Especializado em Reabilitação) na Casa do Idoso Sul"
                        },
                        new
                        {
                            Id = new Guid("366212d2-50af-4f10-974a-7c63174f99c6"),
                            ConclusaoPorcentagem = 100,
                            Descricao = "Criar/estruturar programa com eixos de mente, uso correto de medicamentos, atividades de manutenção e mobilidade.",
                            Detalhes = "",
                            Titulo = "Programa Envelhecimento Saudável"
                        },
                        new
                        {
                            Id = new Guid("c0c11de4-7fbe-493a-a2e5-8d72b0a912ce"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Ampliação do PREVINA para diagnóstico e tratamento de Alzheimer e outras demências.",
                            Detalhes = "",
                            Titulo = "Ampliar atendimento no PREVINA com foco em Alzheimer/demências"
                        },
                        new
                        {
                            Id = new Guid("7f9118da-393d-400c-96a1-d86e5c95196c"),
                            ConclusaoPorcentagem = 50,
                            Descricao = "Ampliar a entrega domiciliar de fraldas, dietas e fórmulas a pacientes elegíveis.",
                            Detalhes = "",
                            Titulo = "Fralda em casa; dietas e fórmulas — ampliar programa"
                        },
                        new
                        {
                            Id = new Guid("cb97679d-e3b5-4949-98bb-48b62d60da1e"),
                            ConclusaoPorcentagem = 50,
                            Descricao = "Entregar medicamentos em domicílio mediante critérios de saúde.",
                            Detalhes = "",
                            Titulo = "Medicamentos em Casa — entrega domiciliar"
                        },
                        new
                        {
                            Id = new Guid("97f84802-cbe5-447b-8615-61504b6c1bf5"),
                            ConclusaoPorcentagem = 50,
                            Descricao = "Revitalização/reformas para melhorar o bem-estar de residentes em ILPIs.",
                            Detalhes = "",
                            Titulo = "Revitalizar e reformar ILPIs (Instituições de Longa Permanência)"
                        },
                        new
                        {
                            Id = new Guid("cbeeaf8c-e41b-44fb-92bd-cf2dc8d39c1d"),
                            ConclusaoPorcentagem = 100,
                            Descricao = "Implantar melhorias na unidade do Sul e reativar o serviço na Leste.",
                            Detalhes = "",
                            Titulo = "Melhorias no Centro Dia (Sul) e reativar Centro Dia (Leste)"
                        },
                        new
                        {
                            Id = new Guid("7fff3ebc-926e-47b2-bac9-fd7f8f92eef1"),
                            ConclusaoPorcentagem = 100,
                            Descricao = "Ampliar o atendimento domiciliar (saúde e assistência) a idosos com dificuldades de locomoção.",
                            Detalhes = "",
                            Titulo = "Ampliar o atendimento domiciliar aos idosos"
                        },
                        new
                        {
                            Id = new Guid("1b4b00d0-4e29-4b4b-bfac-8e1b1b8af04b"),
                            ConclusaoPorcentagem = 100,
                            Descricao = "Oferta regular de cursos de Cuidador de Idosos e correlatos.",
                            Detalhes = "",
                            Titulo = "Ampliar cursos para cuidadores de idosos"
                        },
                        new
                        {
                            Id = new Guid("3ce209e4-6515-4646-9634-70851a07c8bc"),
                            ConclusaoPorcentagem = 100,
                            Descricao = "Expandir participação e calendário da gincana nas Casas do Idoso.",
                            Detalhes = "",
                            Titulo = "Ampliar participação dos idosos na Gincana da Maturidade"
                        },
                        new
                        {
                            Id = new Guid("0617c99b-a07f-43eb-88ef-04266549f11b"),
                            ConclusaoPorcentagem = 100,
                            Descricao = "Incentivar e apoiar delegação joseense nos Jogos Regionais do Idoso (JOMI).",
                            Detalhes = "",
                            Titulo = "Incentivar participação nos Jogos Regionais do Idoso (JOMI)"
                        },
                        new
                        {
                            Id = new Guid("492e1fd6-4b9b-4942-bda9-cc4bb4bc0457"),
                            ConclusaoPorcentagem = 50,
                            Descricao = "Criar um programa focado em renda e qualificação para pessoas idosas.",
                            Detalhes = "",
                            Titulo = "Qualifica o Idoso — programa de geração de renda e capacitação"
                        },
                        new
                        {
                            Id = new Guid("e5386b3d-cbea-499c-8557-56861a96e428"),
                            ConclusaoPorcentagem = 0,
                            Descricao = "Criar um centro especializado de qualificação para idosos.",
                            Detalhes = "",
                            Titulo = "Implantar um Centro de Qualificação do Idoso"
                        },
                        new
                        {
                            Id = new Guid("a99e12f5-90a0-429d-8933-6dae30e6550a"),
                            ConclusaoPorcentagem = 50,
                            Descricao = "Organizar o registro e integrar serviços (saúde, assistência, esporte e cultura) voltados para o idoso.",
                            Detalhes = "",
                            Titulo = "Registro, integração e ampliação dos serviços para o idoso"
                        });
                });

            modelBuilder.Entity("Promessometro.Dominio.Requerimentos.Requerimento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Codigo");

                    b.ToTable("Requerimentos", (string)null);
                });

            modelBuilder.Entity("Promessometro.Dominio.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AceitouOsTermos")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaCriptografada")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("32ec5321-5b2b-4dfe-992b-b9748d035e82"),
                            AceitouOsTermos = true,
                            Email = "adm@gmail.com",
                            Nome = "ADMINISTRADOR",
                            SenhaCriptografada = "1h0ATANFe6x7kMHo1PURE74WI0ayevUwfK/+Ie+IWX/xWrFWngcVUwL/ewryn38EMVMQBFaNo4SaVwgXaBWnDw==",
                            Telefone = ""
                        });
                });

            modelBuilder.Entity("Promessometro.Dominio.Vereadores.Vereador", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CaminhoImagem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Partido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vereadores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("91aa8f43-adb8-4327-965d-29d52a6f5720"),
                            CaminhoImagem = "amelianaomi.jpg",
                            Nome = "Amélia Naomi",
                            Partido = "PT"
                        },
                        new
                        {
                            Id = new Guid("5540a4e3-064e-4d83-84d8-6d23f129e637"),
                            CaminhoImagem = "carlosabranches.jpg",
                            Nome = "Carlos Abranches",
                            Partido = "CIDADANIA"
                        },
                        new
                        {
                            Id = new Guid("ceeb2582-610c-44d1-8618-3e10043a7f27"),
                            CaminhoImagem = "claudioapolinario.jpg",
                            Nome = "Cláudio Apolinário",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("35252558-5c54-40c2-8054-9b7e5e19acd7"),
                            CaminhoImagem = "fabiaozagueiro.jpg",
                            Nome = "Fabião Zagueiro",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("1e2e0c25-7e51-479a-b672-0bb7f0b24605"),
                            CaminhoImagem = "fernandopetiti.jpg",
                            Nome = "Fernando Petiti",
                            Partido = "PSDB"
                        },
                        new
                        {
                            Id = new Guid("3908a6b3-51e9-48e8-b433-caea24dd12a6"),
                            CaminhoImagem = "gilsoncampos.jpg",
                            Nome = "Gilson Campos",
                            Partido = "PRD"
                        },
                        new
                        {
                            Id = new Guid("3915ca1b-78d2-49fe-85d7-8223c73e744c"),
                            CaminhoImagem = "julianafraga.jpg",
                            Nome = "Juliana Fraga",
                            Partido = "PT"
                        },
                        new
                        {
                            Id = new Guid("5b4c7b49-e707-4050-810c-a72bfcb53949"),
                            CaminhoImagem = "linobispo.jpg",
                            Nome = "Lino Bispo",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("15699966-86d5-4d82-9ead-3b1b649145bc"),
                            CaminhoImagem = "marcaodaacademia.jpg",
                            Nome = "Marcão da Academia",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("4890165d-36ed-4165-b2db-80847e6f8af1"),
                            CaminhoImagem = "marcelogarcia.jpg",
                            Nome = "Marcelo Garcia",
                            Partido = "PRD"
                        },
                        new
                        {
                            Id = new Guid("acac26a9-0ed8-41a3-b1be-a757115d9e7e"),
                            CaminhoImagem = "miltonvieirafilho.jpg",
                            Nome = "Milton Vieira Filho",
                            Partido = "REPUBLICANOS"
                        },
                        new
                        {
                            Id = new Guid("beb9ce2a-2c86-4046-b4e5-6e407a042270"),
                            CaminhoImagem = "rafaelpascucci.jpg",
                            Nome = "Rafael Pascucci",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("8d7f5027-6aa1-4192-9c8c-2aa2ecd1dab6"),
                            CaminhoImagem = "renatosantiago.jpg",
                            Nome = "Renato Santiago",
                            Partido = "UNIÃO"
                        },
                        new
                        {
                            Id = new Guid("e146f7b3-9fb6-4cbf-9173-4911a7daa122"),
                            CaminhoImagem = "robertochagas.jpg",
                            Nome = "Roberto Chagas",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("35d94842-8122-471d-99d5-96d297db4e4b"),
                            CaminhoImagem = "robertodoeleven.jpg",
                            Nome = "Roberto do Eleven",
                            Partido = "PSD"
                        },
                        new
                        {
                            Id = new Guid("a16e9e8f-4c53-4cf9-9976-a3f8140e863b"),
                            CaminhoImagem = "rogeriodaacasem.jpg",
                            Nome = "Rogério da Acasem",
                            Partido = "PP"
                        },
                        new
                        {
                            Id = new Guid("23e1cfe8-3b5d-48fd-83c0-d15aa8621a70"),
                            CaminhoImagem = "senna.jpg",
                            Nome = "Senna",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("181aa82a-2bc3-489d-b0e1-cb052e540552"),
                            CaminhoImagem = "sergiocamargo.jpg",
                            Nome = "Sérgio Camargo",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("fc132ac6-609f-48f6-b302-8d910e0fbb9f"),
                            CaminhoImagem = "sidneycampos.jpg",
                            Nome = "Sidney Campos",
                            Partido = "PSDB"
                        },
                        new
                        {
                            Id = new Guid("c524c2e9-ed7f-4fca-a1e5-c866ee967c0a"),
                            CaminhoImagem = "thomazhenrique.jpg",
                            Nome = "Thomaz Henrique",
                            Partido = "PL"
                        },
                        new
                        {
                            Id = new Guid("f15fc27b-dc67-417d-afdb-db2922c336a2"),
                            CaminhoImagem = "zeluis.jpg",
                            Nome = "Zé Luís",
                            Partido = "PSD"
                        });
                });

            modelBuilder.Entity("Promessometro.Dominio.Votos.Voto", b =>
                {
                    b.Property<Guid>("VereadorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequerimentoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Aprovacao")
                        .HasColumnType("boolean");

                    b.HasKey("VereadorId", "RequerimentoId");

                    b.HasIndex("RequerimentoId");

                    b.ToTable("Votos", (string)null);
                });

            modelBuilder.Entity("Promessometro.Dominio.Fases.Fase", b =>
                {
                    b.HasOne("Promessometro.Dominio.Promessas.Promessa", "Promessa")
                        .WithMany("Fases")
                        .HasForeignKey("PromessaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promessa");
                });

            modelBuilder.Entity("Promessometro.Dominio.Votos.Voto", b =>
                {
                    b.HasOne("Promessometro.Dominio.Requerimentos.Requerimento", "Requerimento")
                        .WithMany("Votos")
                        .HasForeignKey("RequerimentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Promessometro.Dominio.Vereadores.Vereador", "Vereador")
                        .WithMany("Votos")
                        .HasForeignKey("VereadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requerimento");

                    b.Navigation("Vereador");
                });

            modelBuilder.Entity("Promessometro.Dominio.Promessas.Promessa", b =>
                {
                    b.Navigation("Fases");
                });

            modelBuilder.Entity("Promessometro.Dominio.Requerimentos.Requerimento", b =>
                {
                    b.Navigation("Votos");
                });

            modelBuilder.Entity("Promessometro.Dominio.Vereadores.Vereador", b =>
                {
                    b.Navigation("Votos");
                });
#pragma warning restore 612, 618
        }
    }
}
