using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Promessometro.Dominio.Promessas;

namespace Promessometro.Infraestrutura.Configurations;

public class PromessaConfiguration : IEntityTypeConfiguration<Promessa>
{
    public void Configure(EntityTypeBuilder<Promessa> builder)
    {
        builder.ToTable("Promessas");

        builder.HasKey(p => p.Id);

        builder.HasData(Promessa.Create("Construir o Novo Hospital da Região Sul, em parceria com a Santa Casa, ampliando o atendimento à população.", "Implantação de um novo hospital público na zona sul de São José dos Campos em colaboração com a Santa Casa. O projeto envolve a doação de terreno municipal (antigo prédio do Pró‑Visão) à instituição, que deve construir e operar o hospital, com parte da estrutura atendendo ao SUS e outra parte podendo ser utilizada por atendimentos privados/complementares, além da realocação de uma UBS no complexo", 10, ""));
        builder.HasData(Promessa.Create("Concluir a ampliação do Hospital de Clínicas Sul, no Parque Industrial, com mais 82 leitos e salas de cirurgia.", "Finalizar a expansão do Hospital de Clínicas Sul, localizado no Parque Industrial de São José dos Campos, incluindo a criação de 82 novos leitos e salas de cirurgia, com o objetivo de aumentar a capacidade de atendimento hospitalar e cirúrgico da região.", 0, ""));
        builder.HasData(Promessa.Create("Implantar o Centro de Imagens do Hospital de Clínicas Sul, em parceria com o Governo do Estado de São Paulo.", "Implantação de um centro de diagnóstico por imagem (tomografia e ressonância magnética) no Hospital de Clínicas Sul, em cooperação técnica e financeira com o Governo do Estado, visando a ampliação da capacidade de exames de média e alta complexidade.", 5, ""));
        builder.HasData(Promessa.Create("Construir a Nova UPA da Região Norte, no Alto da Ponte.", "A promessa consiste na construção de uma nova Unidade de Pronto Atendimento (UPA) para ampliar e qualificar o atendimento de urgência e emergência aos moradores da Região Norte de São José dos Campos, especificamente no bairro Alto da Ponte ou em suas imediações.", 0, ""));
        builder.HasData(Promessa.Create("Construir a Nova UBS Resolve na região do Cajuru.", "Implantação de uma nova UBS Resolve no bairro Cajuru, com estrutura física moderna, atendimento ambulatorial integrado, exames e acolhimento humanizado, conforme diretrizes do modelo UBS Resolve.", 5, ""));
        builder.HasData(Promessa.Create("Construir a Nova UBS Resolve do Pinheirinho dos Palmares, na região sudeste.", "Implantação de uma nova Unidade Básica de Saúde no modelo \"UBS Resolve\", no bairro Pinheirinho dos Palmares, com foco em atendimento integrado, coleta de exames, acolhimento humanizado e infraestrutura moderna para atender à população da região sudeste.", 0, ""));
        builder.HasData(Promessa.Create("Construir a Nova UBS Resolve da Vila Industrial.", "Finalizar a construção da Unidade Básica de Saúde no modelo UBS Resolve, localizada na Vila Industrial (Rua Mizael Marçal), com estrutura moderna e atendimento ambulatorial integrado, conforme previsão de conclusão no mandato iniciado em 1º de janeiro de 2025.", 25, ""));
        builder.HasData(Promessa.Create("Construir a Nova UBS Resolve do Jardim Primavera.", "A promessa visa a construção de uma nova Unidade Básica de Saúde (UBS) com o modelo \"Resolve\" no bairro Jardim Primavera, em São José dos Campos. O objetivo é ampliar e melhorar o acesso aos serviços de saúde primária para os moradores da região, oferecendo um atendimento mais completo e eficiente.", 0, ""));
        builder.HasData(Promessa.Create("Construir a Nova UBS Resolve do Jardim Santa Hermínia.", "Implantar uma Unidade Básica de Saúde no modelo “UBS Resolve” no bairro Jardim Santa Hermínia, oferecendo atendimento ambulatorial integrado, coleta de exames, acolhimento humanizado e estrutura moderna para facilitar o acesso à saúde da população local.", 0, ""));
        builder.HasData(Promessa.Create("Instalar a Nova UBS Resolve do Bosque dos Eucaliptos, no Novo Hospital da Região Sul.", "A promessa é a instalação de uma nova Unidade Básica de Saúde (UBS) no modelo \"Resolve\" dentro do complexo do Novo Hospital da Região Sul, no bairro Bosque dos Eucaliptos. O objetivo é integrar serviços de saúde primária e secundária, oferecendo um atendimento mais completo e acessível à população.", 0, ""));
        builder.HasData(Promessa.Create("Criar a Unidade Avançada de Saúde no Jardim República para atender a região: Vila das Flores, Nova República, Cruzeiro do Sul, Santa Edwiges e adjacências.", "Esta promessa de campanha visa a criação de uma Unidade Avançada de Saúde no bairro Jardim República, em São José dos Campos. O objetivo é expandir o acesso e aprimorar os serviços de saúde para os moradores de uma área específica, incluindo os bairros Vila das Flores, Nova República, Cruzeiro do Sul, Santa Edwiges e adjacências. Essa unidade buscaria oferecer atendimento primário e facilitar o acesso da população local a serviços de saúde essenciais.", 0, ""));
        builder.HasData(Promessa.Create("Criar a Unidade Avançada de Saúde no Urbanova, em parceria com a Univap.", "Esta promessa de campanha visa a criação de uma Unidade Avançada de Saúde no bairro Urbanova, em São José dos Campos. A particularidade dessa unidade é a sua implementação em parceria com a Universidade do Vale do Paraíba (Univap), visando integrar serviços de saúde e possivelmente a expertise acadêmica e de pesquisa da instituição. O intuito é expandir e qualificar o atendimento de saúde para os moradores da região do Urbanova.", 10, ""));
        builder.HasData(Promessa.Create("Criar o Novo Centro de Especialidades Odontológicas.", "Esta promessa de campanha tem como objetivo a criação de um Novo Centro de Especialidades Odontológicas em São José dos Campos. A iniciativa visa expandir e aprimorar os serviços odontológicos especializados oferecidos à população. A promessa faz parte das diretrizes do Plano de Governo sob \"Saúde\" para o ano de 2026, conforme a Lei de Diretrizes Orçamentárias (LDO) 2026.", 10, ""));
        builder.HasData(Promessa.Create("Criar o Novo Centro de Reabilitação Motora e Neurológica, para centralizar e ampliar o atendimento aos pacientes.", "A promessa consiste na construção de um novo centro especializado para reabilitação motora e neurológica, com o objetivo de concentrar os serviços de atendimento e expandir a capacidade de cuidado aos pacientes que necessitam desses tratamentos em São José dos Campos.", 50, ""));
        builder.HasData(Promessa.Create("Criar um Hub de Inovação em Saúde, reunindo startups de saúde digital e IA (Inteligência Artificial), no PIT.", "Esta promessa de campanha visa o estabelecimento de um Hub de Inovação em Saúde em São José dos Campos, localizado no Parque de Inovação Tecnológica (PIT). O objetivo é centralizar e fomentar o desenvolvimento de startups focadas em saúde digital e inteligência artificial.", 0, ""));
        builder.HasData(Promessa.Create("Ampliar o credenciamento de clínicas particulares para oferecer mais consultas com especialistas e exames.", "Esta promessa de campanha tem como objetivo expandir a oferta de consultas com especialistas e exames para a população de São José dos Campos, através do ampliação do credenciamento de clínicas particulares pelo poder público.", 0, ""));
        builder.HasData(Promessa.Create("Ampliar o atendimento no Previna, com o diagnóstico e o tratamento do paciente com câncer em até 60 dias.", "Esta promessa de campanha visa a expansão dos serviços oferecidos pelo programa Previna, em São José dos Campos, com o objetivo de assegurar que o diagnóstico e o tratamento de pacientes com câncer sejam realizados em um prazo máximo de 60 dias. A iniciativa busca agilizar o acesso a esses cuidados essenciais.", 10, ""));
        builder.HasData(Promessa.Create("Fralda em casa, dietas e fórmulas infantis: ampliar o programa para atendimento de mais pacientes.", "A promessa visa expandir o programa de fornecimento de fraldas, dietas e fórmulas infantis para atender um número maior de pacientes necessitados no município de São José dos Campos. O objetivo é aumentar o acesso a esses itens essenciais para a saúde e bem-estar de crianças e outros pacientes que dependem deles.", 0, ""));
        builder.HasData(Promessa.Create("Medicação em casa: entrega de medicamentos de alto custo e uso crônico na casa dos pacientes.", "A promessa tem como objetivo implementar um programa para a entrega de medicamentos de alto custo e de uso contínuo diretamente na residência dos pacientes em São José dos Campos, visando facilitar o acesso e a adesão ao tratamento, especialmente para aqueles com dificuldades de locomoção ou que dependem de medicações específicas.", 0, ""));
        builder.HasData(Promessa.Create("Ampliar o atendimento do Samu.", "A promessa visa expandir a capacidade de atendimento do Serviço de Atendimento Móvel de Urgência (Samu) em São José dos Campos, o que pode envolver o aumento da frota de veículos, a contratação de mais profissionais, a melhoria da infraestrutura ou a otimização dos processos para cobrir uma área maior ou atender mais ocorrências com maior agilidade.", 25, ""));
        builder.HasData(Promessa.Create("Motolância: ampliar o atendimento aos pacientes, numa parceria da Prefeitura/Corpo de Bombeiros/Samu.", "A promessa prevê a expansão do serviço de Motolância em São José dos Campos, buscando otimizar o tempo de resposta em atendimentos de emergência. Isso seria alcançado por meio de uma parceria entre a Prefeitura, o Corpo de Bombeiros e o Samu, visando aprimorar a agilidade e a eficácia no socorro a pacientes.", 0, ""));
        builder.HasData(Promessa.Create("Contratar mais médicos e enfermeiros.", "A promessa visa aumentar o número de profissionais de saúde, especificamente médicos e enfermeiros, na rede pública de São José dos Campos para melhorar o atendimento à população.", 0, ""));
        builder.HasData(Promessa.Create("Ampliar o atendimento de telemedicina.", "A promessa tem como objetivo expandir a oferta e a capacidade dos serviços de saúde prestados remotamente por meio da telemedicina em São José dos Campos, visando facilitar o acesso da população a consultas e atendimentos médicos.", 5, ""));
        builder.HasData(Promessa.Create("Ampliar as Equipes de Saúde da Família.", "A promessa visa aumentar o número e a capacidade das equipes de Saúde da Família em São José dos Campos, com o objetivo de fortalecer a atenção primária e ampliar a cobertura do atendimento de saúde para a população.", 20, ""));
        builder.HasData(Promessa.Create("Ampliar o atendimento especializado de Saúde Mental, nos hospitais Francisca Júlia e Chuí.", "A promessa tem como objetivo aumentar a capacidade e a qualidade dos serviços de saúde mental oferecidos nos hospitais Francisca Júlia e Chuí, proporcionando um atendimento mais abrangente e especializado para a população de São José dos Campos.", 0, ""));
        builder.HasData(Promessa.Create("Manter o atendimento de psicólogos e assistentes sociais nas escolas.", "A promessa visa garantir a continuidade da presença e do trabalho de psicólogos e assistentes sociais nas unidades escolares de São José dos Campos, oferecendo suporte psicossocial e assistência social aos alunos e à comunidade escolar.", 50, ""));
        builder.HasData(Promessa.Create("Ampliar o serviço de testagem de IST (Infecções Sexualmente Transmissíveis) com serviço móvel.", "A promessa visa expandir a capacidade de testagem e detecção de Infecções Sexualmente Transmissíveis em São José dos Campos, por meio da implementação ou ampliação de um serviço de testagem móvel, facilitando o acesso da população aos exames preventivos.", 0, ""));
        builder.HasData(Promessa.Create("Ampliar o serviço de testagem de IST (Infecções Sexualmente Transmissíveis) com serviço móvel.", "A promessa visa expandir a capacidade de testagem e detecção de Infecções Sexualmente Transmissíveis em São José dos Campos, por meio da implementação ou ampliação de um serviço de testagem móvel, facilitando o acesso da população aos exames preventivos.", 0, ""));
        builder.HasData(Promessa.Create("Prontuário eletrônico: consolidar o sistema de informações do histórico do paciente e exames.", "Implantar e integrar um sistema municipal de prontuário eletrônico do paciente para registrar e consolidar históricos médicos e exames em formato digital e unificado, facilitando o acesso e gestão na rede de saúde municipal.", 5, ""));
        builder.HasData(Promessa.Create("Saúde na Mão: modernizar o aplicativo para oferecer mais serviços e facilitar a vida dos usuários.", "A promessa visa atualizar e aprimorar o aplicativo \"Saúde na Mão\" de São José dos Campos, incorporando novas funcionalidades e serviços para torná-lo mais útil e intuitivo, facilitando o acesso dos usuários a informações e atendimentos de saúde.", 0, ""));
        builder.HasData(Promessa.Create("Ações integradas usuários de drogas", "São José Social: a exemplo do Programa São José Unida, desenvolver ações", 100, ""));
        builder.HasData(Promessa.Create("Aumentar vagas de internação", "Ampliar as vagas de internação para o tratamento da dependência química.", 0, ""));
        builder.HasData(Promessa.Create("Atendimento psicológico a dependentes químicos", "Oferecer atendimento psicológico e social online para dar suporte aos", 0, ""));
        builder.HasData(Promessa.Create("Casa de Passagem", "Criar a Casa de Passagem para pessoa em situação de rua", 0, ""));
        builder.HasData(Promessa.Create("Ronda de Apoio Social", "Fortalecer a Ronda de Apoio Social, 24h, em todas as regiões da cidade.", 0, ""));
        builder.HasData(Promessa.Create("Programa “Não Dê Esmola, Dê Cidadania”", "Fortalecer e intensificar o Programa “Não Dê Esmola, Dê Cidadania”.", 0, ""));
        builder.HasData(Promessa.Create("Bom Prato", "Viabilizar a abertura de mais uma unidade do Bom Prato em São José dos", 0, ""));
        builder.HasData(Promessa.Create("Capacitação para moradores de conjuntos habitacionais", "Fazer acompanhamento social e promover oficinas de capacitação", 0, ""));
        builder.HasData(Promessa.Create("Peti (Programa de Erradicação do Trabalho Infantil)", "Fortalecer o Peti (Programa de Erradicação do Trabalho Infantil),", 100, ""));
        builder.HasData(Promessa.Create("Casa da Família Joseense", "Criar a Casa da Família Joseense: com a possibilidade de agregar no", 0, ""));
        builder.HasData(Promessa.Create("Cras (Centro de Referência da Assistência Social)", "Construir a Nova Unidade do Cras, no Campo dos Alemães.", 0, ""));
        builder.HasData(Promessa.Create("Parcerias com o Fundo Social de Solidariedade e entidades sociais", "Consolidar as parcerias com as entidades sociais e com o Fundo Social de", 100, ""));
        builder.HasData(Promessa.Create("Manter os salários em dia e o gatilho salarial do servidor.", "Esta promessa de campanha foca na gestão financeira e de recursos humanos da prefeitura, garantindo o pagamento pontual dos salários dos servidores públicos e a manutenção do gatilho salarial, que assegura reajustes automáticos conforme determinados indicadores de inflação.", 75, ""));
        builder.HasData(Promessa.Create("Garantir a cesta de Natal.", "A promessa de campanha visa assegurar a distribuição de cestas de alimentos, ou um benefício equivalente, para a população de São José dos Campos durante o período natalino. O objetivo é proporcionar apoio alimentar às famílias em vulnerabilidade social no final do ano.", 0, ""));
        builder.HasData(Promessa.Create("Realizar concurso público.", "A promessa consiste na abertura e execução de processos seletivos para o preenchimento de vagas no quadro de servidores da Prefeitura de São José dos Campos, visando a contratação de novos profissionais para diversas áreas da administração pública. Progresso: 75%", 0, ""));
        builder.HasData(Promessa.Create("Realizar concurso público para contratar mais médicos e enfermeiros.", "Esta promessa de campanha visa fortalecer o quadro de profissionais da saúde no município de São José dos Campos, por meio da realização de um concurso público específico para a contratação de médicos e enfermeiros, com o intuito de aprimorar os serviços de saúde oferecidos à população.", 25, ""));
        builder.HasData(Promessa.Create("Realizar concurso público para contratar mais professores e agentes educadores.", "Realizar concursos públicos e/ou processos seletivos para contratação efetiva de professores e agentes educadores na rede municipal de ensino, com o objetivo de fortalecer a educação pública com quadro estabilizado e adequado às demandas escolares atuais.", 5, ""));
        builder.HasData(Promessa.Create("Criar a Escola de Formação em Saúde, um centro de treinamento para qualificar os profissionais da área.", "A promessa visa estabelecer uma instituição dedicada à formação e aprimoramento contínuo de profissionais da área da saúde em São José dos Campos, com o objetivo de elevar a qualidade dos serviços prestados à população.", 0, ""));
        builder.HasData(Promessa.Create("Manter e estimular as atividades de formação continuada para professores e gestores.", "A promessa foca em assegurar a continuidade e impulsionar programas de aprimoramento profissional e educacional para docentes e gestores da rede de ensino de São José dos Campos, visando a melhoria da qualidade da educação.", 0, ""));
        builder.HasData(Promessa.Create("Manter o treinamento contínuo dos GCMs por meio da academia de formação.", "A promessa visa assegurar a continuidade e o aprimoramento constante do treinamento da Guarda Civil Municipal (GCM) de São José dos Campos, utilizando a estrutura da academia de formação para garantir a qualificação e atualização dos profissionais.", 100, ""));
        builder.HasData(Promessa.Create("Manter o programa de bolsa de estudos para os servidores.", "A proposta prevê a continuidade do benefício de bolsa de estudos para servidores municipais, com análise e concessão de bolsas educacionais ou acadêmicas destinadas aos servidores e seus dependentes, conforme critérios estabelecidos pela Prefeitura.", 100, ""));
        builder.HasData(Promessa.Create("Manter as contas do IPSM (Instituto de Previdência do Servidor Municipal) em dia, garantindo as aposentadorias e pensões.", "A promessa tem por objetivo assegurar que o IPSM continue com sua saúde fiscal, realizando os aportes necessários e mantendo em dia o pagamento de aposentadorias e pensões dos servidores municipais, de forma regular e tempestiva.", 30, ""));
        builder.HasData(Promessa.Create("Construir Hospital Público Veterinário", "A construção ainda não foi iniciada, o que existe é um convênio da prefeitura com uma empressa limitado a quem é cadastrado no Cad Único", 0, ""));
        builder.HasData(Promessa.Create("Contrução do novo CCZ (Centro de Controle de Zoonozes)", "Construção não iniciada, porém já existe lei sancionada no Diário Oficial pra essa finalidade, restando agora liberação de recursos orçamentários para a obra.", 0, ""));
        builder.HasData(Promessa.Create("Ampliar o atendimento gratuito do Meu Pet Feliz, programa permanente de castração e chipagem de animais", "Sim, foi ampliado para mais de 1000 vagas por edição, o que é um aumento considerável. Porém, os tutores devem ficar atentos pois as vagas se esgotam muito rápido. Em 2025 já foram realizadas 3 edições de castração e microchipagem diretamente no CCZ.", 100, ""));
        builder.HasData(Promessa.Create("Construção de novos Espaços Caninos", "Não há registro de construções de novos espaços caninos até o momento em 2025. Atualmente existem 16 pela cidade.", 0, ""));
        builder.HasData(Promessa.Create("Promover campanhas de doação de animais e a posse responsável", "Sim, a prefeitura realiza campanha de adoção todos os meses, sempre no último sábado de cada mês. O local é sempre no CCZ.", 100, ""));
        builder.HasData(Promessa.Create("Promover campanha de adoção de animais de médio e grande porte", "Não há registro dessas campanhas no ano de 2025 até o momento. A última ocorreu em abril de 2024", 0, ""));
        builder.HasData(Promessa.Create("Ampliar o programa de distribuição gratuita de vacinação de animais contra a brucelose, raiva do rebanho etc", "Não há registro de ampliação desse programa, apenas a manutenção dos serviços já oferecidos", 0, ""));
        builder.HasData(Promessa.Create("Instalar um PEV (Ponto de Entrega Voluntária) na região do Cajuru", "Não há registro de instalação de um PEV específico na região do Cajuru até o momento. A lista oficial de PEVs da cidade não inclui essa localidade.", 0, ""));
        builder.HasData(Promessa.Create("Ampliar, modernizar e melhorar a gestão dos PEVs", "Houve ampliação do horário de funcionamento e realocação de unidades para melhor atendimento, como no PEV do Campo dos Alemães. Porém, não há expansão significativa em número de unidades.", 50, ""));
        builder.HasData(Promessa.Create("Manter e ampliar a iluminação de LED em toda área urbana (praças, áreas verdes e ciclovia) e rural.", "A meta foi cumprida. 100% da rede pública já utiliza LED, com constante ampliação para áreas verdes, praças e espaços de lazer em todas as regiões.", 100, ""));
        builder.HasData(Promessa.Create("Ampliar a implantação de caminhões elétricos para a coleta de lixo", "Não há registro público ou anúncio oficial de caminhões elétricos em operação no sistema de coleta urbana de São José dos Campos", 0, ""));
        builder.HasData(Promessa.Create("Ampliar o sistema de lixeiras subterrâneas para coleta em pontos de grande concentração de resíduos", "Foi implantado projeto piloto no centro da cidade (Rua Siqueira Campos e Praça João Mendes). Porém, não houve expansão para outras regiões.", 30, ""));
        builder.HasData(Promessa.Create("Coleta com containers em pontos de alta concentração de resíduos", "Contêineres metálicos grandes foram instalados no centro da cidade, em pontos com alta geração de resíduos. Não houve expansão para bairros.", 50, ""));
        builder.HasData(Promessa.Create("Ampliar a modernização dos parques infantis com novos brinquedos, brinquedos inclusivos e piso de borracha", "Diversas praças e parquinhos receberam piso emborrachado e novos brinquedos, mas ainda não há menção clara sobre brinquedos inclusivos em larga escala.", 70, ""));
        builder.HasData(Promessa.Create("Fazer manutenção e melhorias nas estradas rurais", "Não há informações oficiais ou evidências públicas de obras de manutenção ou melhorias em estradas rurais nos anos recentes.", 0, ""));
        builder.HasData(Promessa.Create("Melhorar a coleta de lixo na zona rural, substituindo as lixeiras por contêineres", "Não há confirmação de substituição das lixeiras convencionais por contêineres na zona rural até o momento.", 0, ""));
        builder.HasData(Promessa.Create("Equipar praças e parques com borrifadores para refrescar as crianças e os adultos neste clima de tempo seco", "Não há registro da instalação de borrifadores em praças ou parques da cidade.", 0, ""));
        builder.HasData(Promessa.Create("Criar um novo deck e urbanizar a área verde da Vila Flores, na região sul, com pista de caminhada, quadra esportiva, bancos e área de lazer para as crianças", "Não foram encontrados registros de obras iniciadas ou concluídas nessa área.", 0, ""));
        builder.HasData(Promessa.Create("Melhorar a iluminação da ciclovia na avenida Altos do Rio Doce, no Altos de Santana, beirando o Rio Paraíba", "A cidade ampliou a iluminação em diversas ciclovias, mas não há confirmação específica de que essa ciclovia recebeu nova iluminação.", 0, ""));
        builder.HasData(Promessa.Create("Criar novos decks e revitalizar áreas verdes (Via Cambuí, Praça Rubens Castilho, Mirante no Talude da Veibras).", "A Praça Rubens Castilho foi revitalizada, mas não há obras visíveis ou confirmadas nas demais áreas citadas.", 33, ""));
        builder.HasData(Promessa.Create("Revitalizar as fontes na região central, Praça João Mendes (Praça do Sapo) e ao lado da Univap.", "Não há registro de revitalização das fontes nessas áreas, apenas intervenções relacionadas a lixeiras subterrâneas.", 0, ""));
        builder.HasData(Promessa.Create("Revitalizar as áreas verdes do Vista Verde e Jardim Satélite, com melhoria de iluminação, jardinagem e passeio público.", "O Jardim Satélite recebeu melhorias em anos anteriores. Vista Verde ainda não apresenta registro recente de intervenções.", 50, ""));
        builder.HasData(Promessa.Create("Implantar nova iluminação na SP-50, do bairro Boa Vista até o Buquirinha 1", "Não há comprovação de que a iluminação nesse trecho da SP-50 foi implantada até o momento.", 0, ""));
        builder.HasData(Promessa.Create("Construir mais uma Casa do Idoso na região sul", "Construção de uma nova unidade da Casa do Idoso na região sul.", 0, ""));
        builder.HasData(Promessa.Create("Programa Vida Longa (CDHU) — moradias para idosos", "Viabilizar, com a CDHU/Estado, moradias assistidas para idosos em vulnerabilidade.", 0, ""));
        builder.HasData(Promessa.Create("Criar o novo CER (Centro Especializado em Reabilitação) na Casa do Idoso Sul", "Implantação do CER III no Bosque dos Eucaliptos (atrás da Casa do Idoso Sul).", 50, ""));
        builder.HasData(Promessa.Create("Programa Envelhecimento Saudável", "Criar/estruturar programa com eixos de mente, uso correto de medicamentos, atividades de manutenção e mobilidade.", 100, ""));
        builder.HasData(Promessa.Create("Ampliar atendimento no PREVINA com foco em Alzheimer/demências", "Ampliação do PREVINA para diagnóstico e tratamento de Alzheimer e outras demências.", 0, ""));
        builder.HasData(Promessa.Create("Fralda em casa; dietas e fórmulas — ampliar programa", "Ampliar a entrega domiciliar de fraldas, dietas e fórmulas a pacientes elegíveis.", 50, ""));
        builder.HasData(Promessa.Create("Medicamentos em Casa — entrega domiciliar", "Entregar medicamentos em domicílio mediante critérios de saúde.", 50, ""));
        builder.HasData(Promessa.Create("Revitalizar e reformar ILPIs (Instituições de Longa Permanência)", "Revitalização/reformas para melhorar o bem-estar de residentes em ILPIs.", 50, ""));
        builder.HasData(Promessa.Create("Melhorias no Centro Dia (Sul) e reativar Centro Dia (Leste)", "Implantar melhorias na unidade do Sul e reativar o serviço na Leste.", 100, ""));
        builder.HasData(Promessa.Create("Ampliar o atendimento domiciliar aos idosos", "Ampliar o atendimento domiciliar (saúde e assistência) a idosos com dificuldades de locomoção.", 100, ""));
        builder.HasData(Promessa.Create("Ampliar cursos para cuidadores de idosos", "Oferta regular de cursos de Cuidador de Idosos e correlatos.", 100, ""));
        builder.HasData(Promessa.Create("Ampliar participação dos idosos na Gincana da Maturidade", "Expandir participação e calendário da gincana nas Casas do Idoso.", 100, ""));
        builder.HasData(Promessa.Create("Incentivar participação nos Jogos Regionais do Idoso (JOMI)", "Incentivar e apoiar delegação joseense nos Jogos Regionais do Idoso (JOMI).", 100, ""));
        builder.HasData(Promessa.Create("Qualifica o Idoso — programa de geração de renda e capacitação", "Criar um programa focado em renda e qualificação para pessoas idosas.", 50, ""));
        builder.HasData(Promessa.Create("Implantar um Centro de Qualificação do Idoso", "Criar um centro especializado de qualificação para idosos.", 0, ""));
        builder.HasData(Promessa.Create("Registro, integração e ampliação dos serviços para o idoso", "Organizar o registro e integrar serviços (saúde, assistência, esporte e cultura) voltados para o idoso.", 50, ""));

    }
}